### PR TITLE
Simplify TLS SNI challenge

### PR DESCRIPTION
**Pull request by jsha**
Simplify the TLS SNI challenge by removing the iterations concept, which I believe is not necessary in practice and complicates the protocol needlessly.

### CODE REVIEW

**Comment by kelunik** [comment]
Implementing TLS SNI is currently really complicated, yes.

**Comment by kuba** [comment]
FYI, https://github.com/letsencrypt/letsencrypt/tree/v0.0.0.dev20151108 implements protocol according to the contents of this PR - i.e. without iterations.

**Comment by kuba** [comment]
(so does current Boulder)

**Comment by bifurcation** [comment]
I think this will be OK to land once #54 lands.  

We should consider whether we want to bump the version number in the challenge.  Principle would dictate that we should, since this breaks compatibility with what was published in -01.  But since I'm not aware of any implementation of "tls-sni-01" as specified in -01 (vs. the off-spec implementation in boulder), I'm inclined to just leave it.

**Comment by mholt** [comment]
FWIW on the client side of things, xenolf/lego did not implement the iterations for the tls-sni-01 challenge.

**Comment by hlandau** [comment]
https://github.com/hlandau/acme implements iterations but takes the absence of an "n" parameter to be equivalent to an "n" parameter of 1, which is compatible.

**Comment by bifurcation** [comment]
Great, I'm taking this as sufficient evidence that a version bump is not needed :)

**Pull request merged**
