### PR TITLE
Explicitly forbid to answer GET requests for account info.

### PR DESCRIPTION
**Pull request by joernheissler**
Section "Request Authentication" already forbade it.

### CODE REVIEW

**Comment by bifurcation** [comment]
In general, we have not been making MUST-level requirements for servers in this document because CAs are subject to a lot of external constraints already.  Under that theory, I would say we should just close this.  @cpu @jsha wdyt?

**Comment by joernheissler** [comment]
If you don't want this change, can you change "Servers MUST NOT respond to GET requests for resources that might be considered sensitive. Account resources are the only sensitive resources defined in this specification." instead to resolve the inconsistency?

**Comment by cpu** [comment]
@bifurcation I agree with @joernheissler - this isn't a new MUST-level requirement, it's already said elsewhere that the server MUST NOT respond to sensitive resources and the account object has contact information you wouldn't want returned to an unauthenticated GET request. It seems fine to emphasize this in the account information section.

**Comment by cpu** [comment]
I'm going to merge this. @bifurcation gives an OOB +1.

Thanks @joernheissler !

**Pull request merged**
