### PR TITLE
Remove SCT link relation.

### PR DESCRIPTION
**Pull request by jsha**
This is unlikely to be implemented by any CA, and there is a good
substitute available: servers that want to provide SCTs in a TLS
extension can submit their own certificates. However, even that
will be exceedingly rare as most CAs are planning to embed SCTs
in certificates.

### CODE REVIEW

**Comment by bifurcation** [comment]
This needs WG review before merging.  I don't disagree in principle, especially because it's easy to add back later.  But if there is someone out there who plans to use this, it's not much extra spec.

**Comment by jsha** [comment]
WG review == at IETF meeting, or on mailing list?

**Comment by richsalz** [comment]
Mailing list is where all work is 'officially' done.

**Comment by bifurcation** [comment]
This appears to already have been done.  There is no "sct" link relation in current master.

**Pull request closed without merging**
